### ISSUE TITLE
Comma and semicolon switched

### ISSUE THREAD

**Issue by plhocker** [EconometricInstitute/feb22012-programming-website#5]
Week 2 - Reading and writing files, Filetering a file example code

The code below is incorrect: the try bracket should have a semicolon between the bufferedReader and the printWriter, not a comma.

`public void filter(File in, File out, String pattern) throws IOException {
    try (BufferedReader br = new BufferedReader(new FileReader(in)), PrintWriter pw = new PrintWriter(out)) {
        String line = br.readLine();
        while (line != null) {
            if (line.contains(pattern)) {
                pw.println(line);
            }
            line = br.readLine();
        }
        pw.flush();
   }
}`

I think it should be this:

`public void filter(File in, File out, String pattern) throws IOException {
    try (BufferedReader br = new BufferedReader(new FileReader(in)); PrintWriter pw = new PrintWriter(out)) {
        String line = br.readLine();
        while (line != null) {
            if (line.contains(pattern)) {
                pw.println(line);
            }
            line = br.readLine();
        }
        pw.flush();
   }
}`

**Comment by pcbouman-eur** [comment]
You are right, thank you very much for this comment. I updated this is commit b6a3149d85300b803bd9a2f894438d0da093b00b so it now has been corrected.
